print("this is 1st class")
name="rupak"
print("hello:",name)
print("who are you")
print("i am",input())
print("enter 1st number")
a=int(input())
print("enter 2nd number")
b=int(input())
print("sum:",a+b)
